python: 3.7
node_js: 10

jobs:
  include:
    - stage: Tox Test
      name: "Unit Tests"
      language: python
      python: 3.7
      script: tox

    - stage: Cypress Test
      name: "Frontend Testing Cypress"
      language: node_js
      node_js: 10
      npm: true
      directories:
        - /.npm
        - /.cache
        - node_modules
      install:
        - cd src/router
        - npm ci
      script: npm run cy:run


