- stage: Tox Test
name: "Unit Tests"
language: python
python:
    - 3.7
install: pup install tox-travis
script: tox

- stage: Cypress Test
name: "Frontend testing Cypress"
language: node_js
node_js:
    - 10
cache:
npm: true
directories:
  - ~/.npm
  - ~/.cache
  - node_modules
node_js:
  - '8'
install:
  - cd src/router
  - npm ci
script:
  - npm run cy:run